[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"
  
[build.environment]
  SKIP_PREFLIGHT_CHECK = "true"
  SECRETS_SCAN_OMIT_PATHS = "*.md,backend/**/*.md,env.example,backend/env.example,dist/unity-builds/**/*,public/unity-builds/**/*,unity-build/**/*"
  SECRETS_SCAN_OMIT_KEYS = "VITE_CLERK_PUBLISHABLE_KEY,VITE_GEMINI_API_KEY,NODE_ENV,PORT"
